### ISSUE TITLE
Use System.Text.Json instead of Newtonsoft.Json

### ISSUE THREAD

**Issue by YVbakker** [dendrodocs/dotnet-tool#19]
`System.Text.Json` has been steadily replacing `Newtonsoft.Json`. It's more performant, simpler to use and an official microsoft package: any reason not to switch?

**Comment by eNeRGy164** [comment]
AFAIK, all the (de)serialization of types is not pluggable in `System.Text.Json`.

**Comment by YVbakker** [comment]
what do you mean by pluggable serialization?

**Comment by eNeRGy164** [comment]
Will have to fix some regressions (#22)
